### ISSUE TITLE
Transaction fee estimation

### ISSUE THREAD

**Issue by slavafomin** [tonwhales/ton#2]
Hello!

Is there a way to calculate transaction fee using this library?

What would be the recommended way to check if account has enough funds to carry on the funds transfer?

**Comment by ex3ndr** [comment]
It is a little convoluted, but I am also thinking about fee calculations. As workaround you can use https://toncenter.com/api/v2/#estimateFee directly.

**Comment by ex3ndr** [comment]
Library now have `estimateExternalMessageFee` for fee estimation.
