### ISSUE TITLE
Add V4 contracts

### ISSUE THREAD

**Issue by danya7423** [tonwhales/ton#6]
There is no support for v4 contracts in the libraries, I think it's worth adding.

**Comment by ex3ndr** [comment]
One of the v4 contracts is available at ton-contracts: https://github.com/tonwhales/ton-contracts/blob/master/src/contracts/WalletV4Contract.ts

**Comment by talkol** [comment]
I added a PR to resolve this: https://github.com/tonwhales/ton/pull/17
